codecov:
  require_ci_to_pass: no

coverage:
  round: down
  precision: 2

  status:
    project:
      default:
        informational: true
        paths:
          - "src/"
    patch:
      default:
        target: 80%
        paths:
          - "src/"
    changes: no

comment:
  branches:
    - main
