<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup Label="Analyzers">
    <PackageVersion Include="Rocket.Surgery.Airframe.CodeAnalysis" Version="0.12.1" />
  </ItemGroup>

  <ItemGroup Label="Engine">
    <PackageVersion Include="JsonSchema.Net" Version="9.4.0" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
    <PackageVersion Include="Markdig" Version="1.4.0" />
    <PackageVersion Include="TestableIO.System.IO.Abstractions.Wrappers" Version="22.3.0" />
  </ItemGroup>

  <ItemGroup Label="Cli">
    <PackageVersion Include="Spectre.Console.Cli" Version="0.57.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup Label="Build">
    <PackageVersion Include="Nuke.Common" Version="10.1.0" />
    <PackageVersion Include="NuGet.Packaging" Version="7.9.0" />
    <PackageVersion Include="Rocket.Surgery.Nuke" Version="2.9.12"/>
    <PackageVersion Include="System.Security.Cryptography.Xml" Version="9.0.20" />
  </ItemGroup>

  <ItemGroup Label="Testing">
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="Reqnroll.xunit.v3" Version="3.3.4" />
    <PackageVersion Include="AwesomeAssertions" Version="9.6.0" />
    <PackageVersion Include="Spectre.Console.Cli.Testing" Version="0.57.2" />
    <PackageVersion Include="Rocket.Surgery.Extensions.Testing.AutoFixtures" Version="10.0.6" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.12.0" />
    <PackageVersion Include="TestableIO.System.IO.Abstractions.TestingHelpers" Version="22.3.0" />
  </ItemGroup>

</Project>
