<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>specht</RootNamespace>
    <AssemblyName>specht</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="Markdig" />
  </ItemGroup>

</Project>
