<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Specht.Benchmarks</RootNamespace>
    <AssemblyName>specht.benchmarks</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\specht\specht.csproj" />
  </ItemGroup>

</Project>
